[package]
name = "imgfilters"
version = "0.1.0"
edition = "2021"
src="main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
